### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by mbrowne** [MatAtBread/fast-async#5] opened 2016-06-18 10:16 UTC
I can't get any of the options for this plugin to work...

For example, with this configuration:

	{
	  "plugins":
		["fast-async", {
		  "runtimePattern": "test-input\\.js"
		}]
	}

I get:

`Error: Plugin 1 specified in "/www/derby-boilerplate/.babelrc" provided an invalid property of "runtimePattern"`

I'm running Babel 6.10.1.

**Comment by matAtWork** [comment] 2016-06-18 10:49
I can't reproduce this report.

The example in the README is for babel options in your package.json, which definitely works, as in the test at https://github.com/MatAtBread/fast-async/blob/master/tests/package.json#L24

I just went to the `tests` directory, deleted the "babel" section from the `package.json` and created a `.babelrc` in the same directory:

```
{
    "plugins": [
      "syntax-async-functions",
      ["fast-async",{
              "runtimePattern":"test-input\\.js"
          }]
      ]
  }
```

Running the command line `babel.js test-input.js` works as expected. Changing the runtimePattern filename to something else and re-running the command also works as expected.

My guess is babel is finding and using options from some other source - a nested .babelrc, package.json or some options.

I'll close this for now, but if you get nowhere, create a gist of gh repo with the smallest test case possible and I'll take a look if I can.

**Closed by matAtWork** 2016-06-18 10:49 UTC
